// utils/projectList.ts
import {
  bg1,
  jacanradacar,
  bull_gym,
  mjcleanerservices,
  vaccumProduct,
  ecommercevue,
  ellamarket,
  syndicconnect,
  croams,
  groupearraid,
  mremballage,
  rgp,
  cartonazilal,
  onzosyndic,
  citytiles,
  kna,
  villa_premium,
  majdoline_travel,
  mlb_location,
  jacaranda_car_com,
  jacaranda_moto,
  bike_morocco,
  mbla_association,
  lmansion,
  moov_money,
} from "@/utils/assets";

export const projects = [
  {
    title: "Jacaranda Car Rental Cars",
    image: jacanradacar,
    bg: bg1,
    technologies: ["Laravel", "Next.js", "Tailwindcss"],
    websiteUrl: "https://jacarandacar.fr/",
  },
    {
    title: "Agence KNA",
    image: kna,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://www.agencekna.com/",
  },
  {
    title: "Villa Premium",
    image: villa_premium,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://www.villapremium.fr/",
  },
  {
    title: "Majdoline Travel",
    image: majdoline_travel,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://majdolinetravel.com/",
  },
  {
    title: "Mlb Location",
    image: mlb_location,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://mlb-location.fr/",
  },
  {
    title: "Jacaranda Car",
    image: jacaranda_car_com,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://www.jacarandacar.com/",
  },
  {
    title: "Jacaranda Moto",
    image: jacaranda_moto,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://www.rentalmotomarrakech.com/",
  },
  {
    title: "Bike Morocco",
    image: bike_morocco,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://www.bike-morocco.com/",
  },
  {
    title: "Syndic Connect App",
    image: syndicconnect,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://app.syndicconnect.ma/login",
  },
  {
    title: "Croams App",
    image: croams,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://platform.croams.ma/",
  },
  {
    title: "Groupe Arraid",
    image: groupearraid,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://www.groupearraid.com/",
  },
  {
    title: "Mr Emballage",
    image: mremballage,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://www.mremballage.ma/",
  },
  {
    title: "RGPub",
    image: rgp,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "http://rgp.yancom-creation.com/",
  },
  {
    title: "Carton Azilal",
    image: cartonazilal,
    bg: bg1,
    technologies: ["Laravel", "Jquery - Ajax"],
    websiteUrl: "https://cartonazilal.com/",
  },
  {
    title: "Mbla Association",
    image: mbla_association,
    bg: bg1,
    technologies: ["Wordpress"],
    websiteUrl: "https://www.mblaassociation.org/",
  },
  {
    title: "L Mansion",
    image: lmansion,
    bg: bg1,
    technologies: ["Wordpress"],
    websiteUrl: "https://lmansion.com/",
  },
  {
    title: "Moov Money",
    image: moov_money,
    bg: bg1,
    technologies: ["Wordpress"],
    websiteUrl: "https://moovmoney.ga/",
  },
  {
    title: "Onzo Syndic",
    image: onzosyndic,
    bg: bg1,
    technologies: ["Wordpress"],
    websiteUrl: "https://onzosyndic.com/",
  },
  {
    title: "City Tiles",
    image: citytiles,
    bg: bg1,
    technologies: ["Wordpress"],
    websiteUrl: "https://citytiles.ma/",
  },
  {
    title: "Bull Gym",
    image: bull_gym,
    bg: bg1,
    technologies: ["Next.js", "Tailwindcss", "Shadcn"],
    websiteUrl: "https://bull-gym-seven.vercel.app/",
    githubUrl: "https://github.com/ouzzatDev/bull_gym",
  },
  {
    title: "Vaccum",
    image: vaccumProduct,
    bg: bg1,
    technologies: ["Next.js", "Tailwindcss", "Shadcn"],
    websiteUrl: "https://vaccum-alpha.vercel.app/",
    githubUrl: "https://github.com/ouzzatDev/vaccum",
  },
  {
    title: "MJ Cleaning Services",
    image: mjcleanerservices,
    bg: bg1,
    technologies: ["Next.js", "Tailwindcss", "Shadcn"],
    websiteUrl: "https://mjcleanerservices.vercel.app/",
    githubUrl: "https://gitlab.com/yonneszat/mjcleanerservices",
  },
  {
    title: "Ecommerce Vue App",
    image: ecommercevue,
    bg: bg1,
    technologies: ["Laravel", "Vue js", "Pinia"],
    websiteUrl: "https://ecommerce-web-app-a0346.web.app/",
  },
  {
    title: "Ecommerce Vue App",
    image: ellamarket,
    bg: bg1,
    technologies: ["Laravel", "Vue js", "Vuex"],
    websiteUrl: "https://ellamarket-web-app.web.app/",
  }
];
